"""empty message

Revision ID: 363cf51085f2
Revises: 
Create Date: 2024-09-24 14:32:15.683626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363cf51085f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('eventId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['event.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
